---
name: Build nvim

on:
  push:
    paths:
      - build.sh
    branches:
      - main

  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Which nvim version to build

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          # for *-apple-darwin
          - macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        id: build
        shell: bash
        run: |
          version="${{ github.event.inputs.version }}"
          [ -z "$version" ] || sed -i "s/NVIM_VERSION=.*$/NVIM_VERSION=$version/" build.sh

          ./build.sh

          IFS='=' read -r _ version <<< "$(grep NVIM_VERSION build.sh | head -n1)"
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "date=$(date '+%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: actions/gitea-release-action@v1
        with:
          tag_name: ${{ steps.build.outputs.version }}
          name: ${{ steps.build.outputs.date }}
          make_latest: true
          files: |-
            release/**
