---
name: Build nvim with Github (alpine)

on:
  push:
    paths:
      - build.sh
      - .github/workflows/build-alpine-github.yml
    branches:
      - main

  workflow_dispatch: null

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    container: ghcr.io/mtdcy/baseimage:alpine-3
    strategy:
      matrix:
        # https://github.com/actions/runner-images
        # https://github.com/actions/partner-runner-images
        runner:
          # for x86_64
          - ubuntu-22.04
          # JavaScript Actions in Alpine containers are only supported on x64 Linux runners. Detected Linux Arm64
          # for aarch64
          #- ubuntu-22.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        id: build
        shell: bash
        run: |
          ./build.sh

          IFS='=' read -r _ version <<< "$(grep NVIM_VERSION build.sh | head -n1)"
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "date=$(date '+%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          tag_name: ${{ steps.build.outputs.version }}
          name: ${{ steps.build.outputs.date }}
          make_latest: true
          files: |-
            release/**
