---
name: Build nvim

on:
  push:
    paths:
      - build.sh
      - .github/workflows/build.yml
    branches:
      - main

  workflow_dispatch: null

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.READ_TOKEN }}
          fetch-depth: 2

      - name: Build
        id: build
        run: |
          ./build.sh

          IFS='=' read -r _ version <<< "$(grep NVIM_VERSION build.sh | head -n1)"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: actions/gitea-release-action@v1
        with:
          tag_name: ${{ steps.build.outputs.version }}
          files: |-
            release/**
