---
name: Build nvim with containers

on:
  push:
    paths:
      - build.sh
    branches:
      - main

  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Which nvim version to build

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    container: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:${{ matrix.builder }}
    strategy:
      matrix:
        runner:
          # for x86_64
          - ubuntu-latest
          # for aarch64
          #- macos-arm64
          - ubuntu-latest-arm
        builder:
          # for *-linux-gnu
          - ubuntu-22.04
          # for *-linux-musl
          - alpine-3

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        id: build
        shell: bash
        run: |
          version="${{ github.event.inputs.version }}"
          [ -z "$version" ] || perl -pi -e "s/NVIM_VERSION=.*$/NVIM_VERSION=$version/" build.sh

          IFS='=' read -r _ version <<< "$(grep "NVIM_VERSION=" build.sh | head -n1)"
          echo "version=$version" >> "$GITHUB_OUTPUT"

          ./build.sh

      - name: Release
        uses: actions/gitea-release-action@v1
        with:
          tag_name: ${{ steps.build.outputs.version }}
          name: nvim ${{ steps.build.outputs.version }}
          body: nvim ${{ steps.build.outputs.version }}
          append_body: false
          make_latest: true
          files: |-
            release/**
