---
name: Build nvim with Github

on:
  push:
    paths:
      - build.sh
      - .github/workflows/build-github.yml
    branches:
      - main

  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Which nvim version to build

jobs:
  build:
    runs-on: ${{ matrix.machine }}
    container: ${{ matrix.builder }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # https://github.com/actions/runner-images
          # https://github.com/actions/partner-runner-images
          # for arm64-apple-darwin
          - machine: macos-14
          # for x86_64-apple-darwin
          - machine: macos-13
          # for x86_64-linux-gnu
          - machine: ubuntu-22.04
            builder: ghcr.io/mtdcy/builder:ubuntu-22.04
          # for x86_64-linux-musl
          - machine: ubuntu-22.04
            builder: ghcr.io/mtdcy/builder:alpine-3
          # for aarch64-linux-gnu
          - machine: ubuntu-22.04-arm
            builder: ghcr.io/mtdcy/builder:ubuntu-22.04
          # no aarch64-linux-musl, as
          # JavaScript Actions in Alpine containers are only supported on x64 Linux runners. Detected Linux Arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        id: build
        shell: bash
        run: |
          version="${{ github.event.inputs.version }}"
          [ -z "$version" ] || perl -pi -e "s/NVIM_VERSION=.*$/NVIM_VERSION=$version/" build.sh

          IFS='=' read -r _ version <<< "$(grep "NVIM_VERSION=" build.sh | head -n1)"
          echo "version=$version" >> "$GITHUB_OUTPUT"

          ./build.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          tag_name: ${{ steps.build.outputs.version }}
          name: nvim ${{ steps.build.outputs.version }}
          body: nvim ${{ steps.build.outputs.version }}
          append_body: false
          make_latest: true
          files: |-
            release/**
